// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzb5ojfqdCv-kc-GctjtaeIgIZEIHDl0U',
    appId: '1:911947193559:web:e38fd1431d8c8d4ec1e492',
    messagingSenderId: '911947193559',
    projectId: 'chatupapp-d8ef2',
    authDomain: 'chatupapp-d8ef2.firebaseapp.com',
    storageBucket: 'chatupapp-d8ef2.firebasestorage.app',
    measurementId: 'G-0R11VN6F8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQezhd_2fQ1FdYzVF3l8tRsp6y1k6aDxY',
    appId: '1:911947193559:android:ba9731b1bbf97065c1e492',
    messagingSenderId: '911947193559',
    projectId: 'chatupapp-d8ef2',
    storageBucket: 'chatupapp-d8ef2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9XD-oJ5e_FYQ3CuJCoPVsDrtSFa7gCC8',
    appId: '1:911947193559:ios:43828cbe646ae4dac1e492',
    messagingSenderId: '911947193559',
    projectId: 'chatupapp-d8ef2',
    storageBucket: 'chatupapp-d8ef2.firebasestorage.app',
    iosBundleId: 'com.example.chatappReal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9XD-oJ5e_FYQ3CuJCoPVsDrtSFa7gCC8',
    appId: '1:911947193559:ios:43828cbe646ae4dac1e492',
    messagingSenderId: '911947193559',
    projectId: 'chatupapp-d8ef2',
    storageBucket: 'chatupapp-d8ef2.firebasestorage.app',
    iosBundleId: 'com.example.chatappReal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzb5ojfqdCv-kc-GctjtaeIgIZEIHDl0U',
    appId: '1:911947193559:web:f5324b129d9a7cebc1e492',
    messagingSenderId: '911947193559',
    projectId: 'chatupapp-d8ef2',
    authDomain: 'chatupapp-d8ef2.firebaseapp.com',
    storageBucket: 'chatupapp-d8ef2.firebasestorage.app',
    measurementId: 'G-F2HTW3TXDW',
  );
}
